version: "3.6"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: demoDB
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    ports:
      - "5430:5432"